"""One-shot helper to apply structural edits to the notebooks.
Run once: python scripts/_patch_notebooks.py
Idempotent — re-running just rewrites the cells from the templates below.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def md(src):
    return {"cell_type": "markdown", "metadata": {}, "source": src.splitlines(keepends=True)}


def code(src):
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": src.splitlines(keepends=True)}


# ===================== 00_setup.ipynb =====================
def patch_setup():
    nb_path = ROOT / "00_setup.ipynb"
    nb = json.loads(nb_path.read_text(encoding="utf-8"))

    cells = []
    # Header
    cells.append(md(
        "# 00 · Setup — Connections and Schema Creation\n"
        "\n"
        "This notebook is the starting point for the ELT pipeline of the WWI Data Warehouse.\n"
        "\n"
        "**What this notebook does:**\n"
        "1. Defines the connection parameters for the two databases\n"
        "2. Tests the connections (operational source and DW) — split per VPN state\n"
        "3. Creates the `bronze`, `silver`, and `gold` schemas in the DW database\n"
        "4. Creates the `bronze._load_control` table for ELT metadata\n"
        "5. Creates the tables for the `gold` layer (dimensions and fact tables)\n"
        "6. Validates the created structure\n"
        "\n"
        "---\n"
        "**VPN constraint** — the operational source (`postgres2.ipca.pt`) requires VPN ON, while Supabase is reachable only with VPN OFF. Cells that touch each are kept separate so you can toggle VPN between them.\n"
    ))

    cells.append(md(
        "## 1. Installation of dependencies"
    ))
    cells.append(code("%pip install -r requirements.txt --quiet"))

    cells.append(md(
        "## 2. Connection parameters\n"
        "\n"
        "Credentials are loaded from the `.env` file in the same folder."
    ))
    cells.append(code(
        "from dotenv import load_dotenv\n"
        "import os\n"
        "\n"
        "load_dotenv(override=True)\n"
        "\n"
        "# -- Operational Source -------------------------------------------------------\n"
        "SRC_HOST     = os.getenv(\"SRC_HOST\")\n"
        "SRC_PORT     = int(os.getenv(\"SRC_PORT\", 5432))\n"
        "SRC_DB       = os.getenv(\"SRC_DB\")\n"
        "SRC_USER     = os.getenv(\"SRC_USER\")\n"
        "SRC_PASSWORD = os.getenv(\"SRC_PASSWORD\")\n"
        "\n"
        "# -- Data Warehouse (Supabase) ------------------------------------------------\n"
        "SUPABASE_URL  = os.getenv(\"SUPABASE_URL\")\n"
        "SUPABASE_PORT = int(os.getenv(\"SUPABASE_PORT\", 5432))\n"
        "SUPABASE_DB   = os.getenv(\"SUPABASE_DB\")\n"
        "SUPABASE_USER = os.getenv(\"SUPABASE_USER\")\n"
        "SUPABASE_PASSWORD = os.getenv(\"SUPABASE_PASSWORD\")\n"
        "\n"
        "SCHEMAS = [\"bronze\", \"silver\", \"gold\"]\n"
        "\n"
        "print(f\"SRC: {SRC_USER}@{SRC_HOST}:{SRC_PORT}/{SRC_DB}\")\n"
        "print(f\"Supabase: {SUPABASE_USER}@{SUPABASE_URL}:{SUPABASE_PORT}/{SUPABASE_DB}\")\n"
    ))

    cells.append(md(
        "## 3. Engine factory + DWH engine (run with VPN OFF)\n"
        "\n"
        "Creates the SQLAlchemy engine pointing to Supabase. Run this cell with VPN OFF."
    ))
    cells.append(code(
        "from sqlalchemy import create_engine, text\n"
        "from sqlalchemy.engine import URL\n"
        "\n"
        "def make_engine(host, port, db, user, password, sslmode=None):\n"
        "    return create_engine(URL.create(\"postgresql+psycopg2\", username=user, password=password, host=host, port=port, database=db, query={\"sslmode\": sslmode} if sslmode else None))\n"
        "\n"
        "if not all([SUPABASE_URL, SUPABASE_DB, SUPABASE_USER, SUPABASE_PASSWORD]):\n"
        "    raise ValueError(\"SUPABASE_URL, SUPABASE_DB, SUPABASE_USER and SUPABASE_PASSWORD must be set in .env\")\n"
        "engine_dwh = make_engine(SUPABASE_URL, SUPABASE_PORT, SUPABASE_DB, SUPABASE_USER, SUPABASE_PASSWORD, sslmode=\"require\")\n"
        "print(\"✓ engine_dwh created.\")\n"
    ))

    cells.append(md(
        "## 4. Source engine (run with VPN ON, optional)\n"
        "\n"
        "Only needed if you want to test the source connection or run the validation query in section 8 (cell `## 8`). Skip this cell if you don't have VPN."
    ))
    cells.append(code(
        "engine_src = make_engine(SRC_HOST, SRC_PORT, SRC_DB, SRC_USER, SRC_PASSWORD)\n"
        "print(\"✓ engine_src created (requires VPN ON to actually connect).\")\n"
    ))

    cells.append(md(
        "## 5a. Test DWH connection (VPN OFF)"
    ))
    cells.append(code(
        "def test_connection(engine, label):\n"
        "    try:\n"
        "        with engine.connect() as conn:\n"
        "            result = conn.execute(text(\"SELECT current_database(), version()\"))\n"
        "            db_name, version = result.fetchone()\n"
        "            print(f\"✓ {label}\")\n"
        "            print(f\"  Database : {db_name}\")\n"
        "            print(f\"  Version  : {version.split(',')[0]}\")\n"
        "    except Exception as e:\n"
        "        print(f\"✗ {label} — ERROR: {e}\")\n"
        "\n"
        "test_connection(engine_dwh, \"Data Warehouse (Supabase)\")\n"
    ))

    cells.append(md(
        "## 5b. Test source connection (VPN ON)\n"
        "\n"
        "Run this cell only when connected to the VPN."
    ))
    cells.append(code(
        "test_connection(engine_src, \"Operational Source (wwi)\")\n"
    ))

    cells.append(md(
        "## 6. Medallion architecture schemas (VPN OFF)\n"
        "\n"
        "Creates the three schemas in the DW. Idempotent."
    ))
    cells.append(code(
        "with engine_dwh.begin() as conn:\n"
        "    for schema in SCHEMAS:\n"
        "        conn.execute(text(f\"CREATE SCHEMA IF NOT EXISTS {schema}\"))\n"
        "        print(f\"✓ Schema '{schema}' created (or already exists)\")\n"
        "\n"
        "print(\"\\nMedallion architecture schemas ready.\")\n"
    ))

    cells.append(md(
        "## 7. ELT metadata table `bronze._load_control` (VPN OFF)\n"
        "\n"
        "Tracks every load attempt against bronze tables. Used by `01_bronze.ipynb` and `99_verification.py`. Created here so it exists even before the bronze pipeline runs the first time."
    ))
    cells.append(code(
        "DDL_CONTROL = \"\"\"\n"
        "CREATE TABLE IF NOT EXISTS bronze._load_control (\n"
        "    table_name VARCHAR(100) NOT NULL,\n"
        "    strategy VARCHAR(20) NOT NULL,\n"
        "    snapshot_id INT,\n"
        "    watermark_date DATE,\n"
        "    loaded_at TIMESTAMP NOT NULL,\n"
        "    rows_total INT,\n"
        "    rows_inserted INT,\n"
        "    rows_updated INT,\n"
        "    rows_deleted INT,\n"
        "    status VARCHAR(20) NOT NULL,\n"
        "    PRIMARY KEY (table_name, loaded_at)\n"
        ");\n"
        "\"\"\"\n"
        "with engine_dwh.begin() as conn:\n"
        "    conn.execute(text(DDL_CONTROL))\n"
        "print(\"✓ bronze._load_control ready.\")\n"
    ))

    cells.append(md(
        "## 8. Creation of Gold layer tables (VPN OFF)\n"
        "\n"
        "**Dimensions:** DimEmployee, DimCustomer, DimLocation, DimDate, DimProduct, DimDeliveryMethod, DimPaymentMethod.\n"
        "\n"
        "**Fact tables:** FactSales (line level), FactInvoices (header level).\n"
        "\n"
        "All SCD Type 2 dimensions carry `version`, `date_from`, `date_to`. The current row has `date_to IS NULL`."
    ))
    cells.append(code(
        "DDL_GOLD = \"\"\"\n"
        "-- DimEmployee\n"
        "CREATE TABLE IF NOT EXISTS gold.DimEmployee (\n"
        "    EmployeeKey SERIAL PRIMARY KEY,\n"
        "    version INT NOT NULL,\n"
        "    date_from TIMESTAMP NOT NULL,\n"
        "    date_to TIMESTAMP,\n"
        "    PersonID INT NOT NULL,\n"
        "    FullName VARCHAR(255),\n"
        "    IsSalesperson INT\n"
        ");\n"
        "\n"
        "-- DimCustomer\n"
        "CREATE TABLE IF NOT EXISTS gold.DimCustomer (\n"
        "    CustomerKey SERIAL PRIMARY KEY,\n"
        "    version INT NOT NULL,\n"
        "    date_from TIMESTAMP NOT NULL,\n"
        "    date_to TIMESTAMP,\n"
        "    CustomerID INT NOT NULL,\n"
        "    CustomerName VARCHAR(255),\n"
        "    Category VARCHAR(255)\n"
        ");\n"
        "\n"
        "-- DimLocation\n"
        "CREATE TABLE IF NOT EXISTS gold.DimLocation (\n"
        "    LocationKey SERIAL PRIMARY KEY,\n"
        "    version INT NOT NULL,\n"
        "    date_from TIMESTAMP NOT NULL,\n"
        "    date_to TIMESTAMP,\n"
        "    LocationID INT NOT NULL,\n"
        "    City VARCHAR(255),\n"
        "    State VARCHAR(255),\n"
        "    Country VARCHAR(255),\n"
        "    SalesTerritory VARCHAR(50)\n"
        ");\n"
        "\n"
        "-- DimDate\n"
        "CREATE TABLE IF NOT EXISTS gold.DimDate (\n"
        "    DateKey INT PRIMARY KEY,\n"
        "    Date DATE,\n"
        "    Year INT,\n"
        "    Month INT,\n"
        "    Day INT\n"
        ");\n"
        "\n"
        "-- DimProduct\n"
        "CREATE TABLE IF NOT EXISTS gold.DimProduct (\n"
        "    ProductKey SERIAL PRIMARY KEY,\n"
        "    version INT NOT NULL,\n"
        "    date_from TIMESTAMP NOT NULL,\n"
        "    date_to TIMESTAMP,\n"
        "    StockItemID INT NOT NULL,\n"
        "    StockItemName VARCHAR(255),\n"
        "    Brand VARCHAR(255)\n"
        ");\n"
        "\n"
        "-- DimDeliveryMethod\n"
        "CREATE TABLE IF NOT EXISTS gold.DimDeliveryMethod (\n"
        "    DeliveryMethodKey SERIAL PRIMARY KEY,\n"
        "    version INT NOT NULL,\n"
        "    date_from TIMESTAMP NOT NULL,\n"
        "    date_to TIMESTAMP,\n"
        "    DeliveryMethodID INT NOT NULL,\n"
        "    DeliveryMethodName VARCHAR(255)\n"
        ");\n"
        "\n"
        "-- DimPaymentMethod\n"
        "CREATE TABLE IF NOT EXISTS gold.DimPaymentMethod (\n"
        "    PaymentMethodKey SERIAL PRIMARY KEY,\n"
        "    version INT NOT NULL,\n"
        "    date_from TIMESTAMP NOT NULL,\n"
        "    date_to TIMESTAMP,\n"
        "    PaymentMethodID INT NOT NULL,\n"
        "    PaymentMethodName VARCHAR(255)\n"
        ");\n"
        "\n"
        "-- FactSales (Line Level)\n"
        "CREATE TABLE IF NOT EXISTS gold.FactSales (\n"
        "    SalesKey SERIAL PRIMARY KEY,\n"
        "    InvoiceID INT,\n"
        "    DateKey INT,\n"
        "    EmployeeKey INT,\n"
        "    CustomerKey INT,\n"
        "    ProductKey INT,\n"
        "    LocationKey INT,\n"
        "    Quantity INT,\n"
        "    UnitPrice NUMERIC(10,2),\n"
        "    TaxAmount NUMERIC(10,2),\n"
        "    ExtendedPrice NUMERIC(10,2),\n"
        "    LineProfit NUMERIC(10,2),\n"
        "    FOREIGN KEY (DateKey) REFERENCES gold.DimDate(DateKey),\n"
        "    FOREIGN KEY (EmployeeKey) REFERENCES gold.DimEmployee(EmployeeKey),\n"
        "    FOREIGN KEY (CustomerKey) REFERENCES gold.DimCustomer(CustomerKey),\n"
        "    FOREIGN KEY (ProductKey) REFERENCES gold.DimProduct(ProductKey),\n"
        "    FOREIGN KEY (LocationKey) REFERENCES gold.DimLocation(LocationKey)\n"
        ");\n"
        "\n"
        "-- FactInvoices (Header Level)\n"
        "CREATE TABLE IF NOT EXISTS gold.FactInvoices (\n"
        "    InvoiceFactKey SERIAL PRIMARY KEY,\n"
        "    InvoiceID INT,\n"
        "    DateKey INT,\n"
        "    EmployeeKey INT,\n"
        "    CustomerKey INT,\n"
        "    LocationKey INT,\n"
        "    AccountsEmployeeKey INT,\n"
        "    DeliveryMethodKey INT,\n"
        "    InvoiceAmount NUMERIC(10,2),\n"
        "    PaymentDelay_Days INT,\n"
        "    OutstandingBalance NUMERIC(10,2),\n"
        "    FOREIGN KEY (DateKey) REFERENCES gold.DimDate(DateKey),\n"
        "    FOREIGN KEY (EmployeeKey) REFERENCES gold.DimEmployee(EmployeeKey),\n"
        "    FOREIGN KEY (CustomerKey) REFERENCES gold.DimCustomer(CustomerKey),\n"
        "    FOREIGN KEY (LocationKey) REFERENCES gold.DimLocation(LocationKey),\n"
        "    FOREIGN KEY (AccountsEmployeeKey) REFERENCES gold.DimEmployee(EmployeeKey),\n"
        "    FOREIGN KEY (DeliveryMethodKey) REFERENCES gold.DimDeliveryMethod(DeliveryMethodKey)\n"
        ");\n"
        "\"\"\"\n"
        "\n"
        "with engine_dwh.begin() as conn:\n"
        "    conn.execute(text(DDL_GOLD))\n"
        "\n"
        "print(\"✓ Gold layer tables successfully created.\")\n"
    ))

    cells.append(md(
        "## 9. Validation — Inventory of created schemas and tables (VPN OFF)"
    ))
    cells.append(code(
        "import pandas as pd\n"
        "\n"
        "query = \"\"\"\n"
        "    SELECT table_schema AS schema, table_name, table_type AS type\n"
        "    FROM information_schema.tables\n"
        "    WHERE table_schema IN ('bronze', 'silver', 'gold')\n"
        "    ORDER BY table_schema, table_name\n"
        "\"\"\"\n"
        "with engine_dwh.connect() as conn:\n"
        "    df = pd.read_sql(text(query), conn)\n"
        "print(\"Objects created in the DW:\")\n"
        "print(df.to_string(index=False))\n"
    ))

    cells.append(md(
        "## 10. Validation — Operational source tables (VPN ON)\n"
        "\n"
        "Run this cell only when connected to the VPN."
    ))
    cells.append(code(
        "import pandas as pd\n"
        "\n"
        "query_src = \"\"\"\n"
        "    SELECT t.table_name,\n"
        "           (SELECT COUNT(*) FROM information_schema.columns c\n"
        "             WHERE c.table_name = t.table_name AND c.table_schema = 'public') AS columns\n"
        "    FROM information_schema.tables t\n"
        "    WHERE t.table_schema = 'public' AND t.table_type = 'BASE TABLE'\n"
        "    ORDER BY t.table_name\n"
        "\"\"\"\n"
        "with engine_src.connect() as conn:\n"
        "    df_src = pd.read_sql(text(query_src), conn)\n"
        "print(f\"Tables in operational source ({SRC_DB}):\")\n"
        "print(df_src.to_string(index=False))\n"
    ))

    cells.append(md(
        "## 11. Summary\n"
        "\n"
        "| Step | VPN | Status |\n"
        "|---|---|---|\n"
        "| Connection to DW | OFF | ✓ |\n"
        "| Connection to source | ON  | ✓ |\n"
        "| `bronze` / `silver` / `gold` schemas | OFF | ✓ |\n"
        "| `bronze._load_control` | OFF | ✓ |\n"
        "| Gold tables | OFF | ✓ |\n"
        "\n"
        "**Next step:** execute `01_bronze.ipynb`."
    ))

    nb["cells"] = cells
    nb_path.write_text(json.dumps(nb, indent=1, ensure_ascii=False), encoding="utf-8")
    print(f"Patched {nb_path.name}: {len(cells)} cells")


# ===================== 01_bronze.ipynb =====================
def patch_bronze():
    nb_path = ROOT / "01_bronze.ipynb"
    nb = json.loads(nb_path.read_text(encoding="utf-8"))
    cells = []

    cells.append(md(
        "# 01 · Bronze — Source extraction → CSV → DWH\n"
        "\n"
        "Two-phase, VPN-aware extraction:\n"
        "- **Phase A (VPN ON):** read source DB, save CSVs locally, also save column schema JSONs.\n"
        "- **Phase B (VPN OFF):** read CSVs, derive bronze table DDL from the saved schema, diff against last snapshot, write to `bronze.*` and register the load.\n"
        "\n"
        "Bronze is now **faithful to the source** — every column from each source table lands in bronze. Column projections happen later in silver.\n"
    ))

    cells.append(md(
        "## 1. Imports and env"
    ))
    cells.append(code(
        "import json\n"
        "import pandas as pd\n"
        "import hashlib\n"
        "from datetime import datetime, date, timezone\n"
        "from pathlib import Path\n"
        "from sqlalchemy import create_engine, text\n"
        "from sqlalchemy.engine import URL\n"
        "from dotenv import load_dotenv\n"
        "import os\n"
        "\n"
        "load_dotenv(override=True)\n"
        "\n"
        "SRC_HOST     = os.getenv(\"SRC_HOST\")\n"
        "SRC_PORT     = int(os.getenv(\"SRC_PORT\", 5432))\n"
        "SRC_DB       = os.getenv(\"SRC_DB\")\n"
        "SRC_USER     = os.getenv(\"SRC_USER\")\n"
        "SRC_PASSWORD = os.getenv(\"SRC_PASSWORD\")\n"
        "\n"
        "SUPABASE_URL  = os.getenv(\"SUPABASE_URL\")\n"
        "SUPABASE_PORT = int(os.getenv(\"SUPABASE_PORT\", 5432))\n"
        "SUPABASE_DB   = os.getenv(\"SUPABASE_DB\")\n"
        "SUPABASE_USER = os.getenv(\"SUPABASE_USER\")\n"
        "SUPABASE_PASSWORD = os.getenv(\"SUPABASE_PASSWORD\")\n"
        "\n"
        "def make_engine(host, port, db, user, password, sslmode=None):\n"
        "    return create_engine(URL.create(\"postgresql+psycopg2\", username=user, password=password, host=host, port=port, database=db, query={\"sslmode\": sslmode} if sslmode else None))\n"
        "\n"
        "print(\"Env loaded. Create engine_src (VPN ON) or engine_dwh (VPN OFF) in the next cells.\")\n"
    ))

    cells.append(md(
        "## 2. engine_src — VPN ON"
    ))
    cells.append(code(
        "engine_src = make_engine(SRC_HOST, SRC_PORT, SRC_DB, SRC_USER, SRC_PASSWORD)\n"
        "with engine_src.connect() as conn:\n"
        "    print(\"✓ engine_src connected:\", conn.execute(text(\"SELECT current_database()\")).scalar())\n"
    ))

    cells.append(md(
        "## 3. engine_dwh — VPN OFF"
    ))
    cells.append(code(
        "if not all([SUPABASE_URL, SUPABASE_DB, SUPABASE_USER, SUPABASE_PASSWORD]):\n"
        "    raise ValueError(\"SUPABASE env vars missing\")\n"
        "engine_dwh = make_engine(SUPABASE_URL, SUPABASE_PORT, SUPABASE_DB, SUPABASE_USER, SUPABASE_PASSWORD, sslmode=\"require\")\n"
        "with engine_dwh.connect() as conn:\n"
        "    print(\"✓ engine_dwh connected:\", conn.execute(text(\"SELECT current_database()\")).scalar())\n"
    ))

    cells.append(md(
        "## 4. Table catalog\n"
        "\n"
        "Snapshot tables are full-reloaded each run; date tables are appended incrementally based on a watermark column."
    ))
    cells.append(code(
        "SNAPSHOT_TABLES = [\n"
        "    {\"src\": \"people\", \"dest\": \"people\", \"pk\": [\"personid\"]},\n"
        "    {\"src\": \"customercategories\", \"dest\": \"customercategories\", \"pk\": [\"customercategoryid\"]},\n"
        "    {\"src\": \"customers\", \"dest\": \"customers\", \"pk\": [\"customerid\"]},\n"
        "    {\"src\": \"countries\", \"dest\": \"countries\", \"pk\": [\"countryid\"]},\n"
        "    {\"src\": \"stateprovinces\", \"dest\": \"stateprovinces\", \"pk\": [\"stateprovinceid\"]},\n"
        "    {\"src\": \"cities\", \"dest\": \"cities\", \"pk\": [\"cityid\"]},\n"
        "    {\"src\": \"stockitems\", \"dest\": \"stockitems\", \"pk\": [\"stockitemid\"]},\n"
        "    {\"src\": \"customertransactions\", \"dest\": \"customertransactions\", \"pk\": [\"customertransactionid\"]},\n"
        "    {\"src\": \"deliverymethods\", \"dest\": \"deliverymethods\", \"pk\": [\"deliverymethodid\"]},\n"
        "    {\"src\": \"paymentmethods\", \"dest\": \"paymentmethods\", \"pk\": [\"paymentmethodid\"]},\n"
        "    {\"src\": \"transactiontypes\", \"dest\": \"transactiontypes\", \"pk\": [\"transactiontypeid\"]},\n"
        "]\n"
        "\n"
        "DATE_TABLES = [\n"
        "    {\"src\": \"invoices\", \"dest\": \"invoices\", \"watermark\": \"invoicedate\", \"pk\": [\"invoiceid\"]},\n"
        "    {\"src\": \"invoicelines\", \"dest\": \"invoicelines\", \"watermark\": \"invoicedate\", \"pk\": [\"invoicelineid\"]},\n"
        "]\n"
        "\n"
        "SNAP_META_COLS = {\n"
        "    \"_snapshot_id\": \"INT NOT NULL\",\n"
        "    \"_loaded_at\": \"TIMESTAMP NOT NULL\",\n"
        "    \"_change_op\": \"VARCHAR(10) NOT NULL\",\n"
        "    \"_source\": \"VARCHAR(100) NOT NULL\",\n"
        "}\n"
        "DATE_META_COLS = {\n"
        "    \"_loaded_at\": \"TIMESTAMP NOT NULL\",\n"
        "    \"_source\": \"VARCHAR(100) NOT NULL\",\n"
        "}\n"
    ))

    cells.append(md(
        "## 5. _load_control table (VPN OFF)\n"
        "\n"
        "Already created by `00_setup.ipynb`. This cell ensures it exists if you skipped setup."
    ))
    cells.append(code(
        "DDL_CONTROL = \"\"\"\n"
        "CREATE TABLE IF NOT EXISTS bronze._load_control (\n"
        "    table_name VARCHAR(100) NOT NULL,\n"
        "    strategy VARCHAR(20) NOT NULL,\n"
        "    snapshot_id INT,\n"
        "    watermark_date DATE,\n"
        "    loaded_at TIMESTAMP NOT NULL,\n"
        "    rows_total INT,\n"
        "    rows_inserted INT,\n"
        "    rows_updated INT,\n"
        "    rows_deleted INT,\n"
        "    status VARCHAR(20) NOT NULL,\n"
        "    PRIMARY KEY (table_name, loaded_at)\n"
        ");\n"
        "\"\"\"\n"
        "with engine_dwh.begin() as conn:\n"
        "    conn.execute(text(DDL_CONTROL))\n"
        "print(\"✓ bronze._load_control ready.\")\n"
    ))

    cells.append(md(
        "## 6. Helper functions\n"
        "\n"
        "All helpers below operate on `engine_dwh` only (VPN OFF). They handle:\n"
        "- snapshot id allocation per table\n"
        "- last-active-snapshot retrieval (excludes DELETE rows)\n"
        "- row-level diff via MD5 hash\n"
        "- load_control INSERT\n"
        "- watermark retrieval for incremental tables\n"
        "- DDL generation from a saved source schema JSON"
    ))
    cells.append(code(
        "PG_TYPE_MAP = {\n"
        "    \"integer\": \"INT\", \"bigint\": \"BIGINT\", \"smallint\": \"SMALLINT\",\n"
        "    \"text\": \"TEXT\", \"character varying\": \"TEXT\", \"character\": \"TEXT\",\n"
        "    \"date\": \"DATE\", \"timestamp without time zone\": \"TIMESTAMP\", \"timestamp with time zone\": \"TIMESTAMPTZ\",\n"
        "    \"numeric\": \"NUMERIC\", \"real\": \"REAL\", \"double precision\": \"DOUBLE PRECISION\",\n"
        "    \"boolean\": \"BOOLEAN\", \"bytea\": \"BYTEA\", \"uuid\": \"UUID\", \"json\": \"JSONB\", \"jsonb\": \"JSONB\",\n"
        "}\n"
        "\n"
        "def map_pg_type(data_type):\n"
        "    return PG_TYPE_MAP.get(data_type.lower(), \"TEXT\")\n"
        "\n"
        "def ensure_bronze_table(dest, schema_json, meta_cols):\n"
        "    \"\"\"Create bronze.<dest> from a list of {column_name, data_type} entries plus the metadata columns.\"\"\"\n"
        "    cols_sql = []\n"
        "    for entry in schema_json:\n"
        "        cols_sql.append(f\"{entry['column_name']} {map_pg_type(entry['data_type'])}\")\n"
        "    for col, ddl in meta_cols.items():\n"
        "        cols_sql.append(f\"{col} {ddl}\")\n"
        "    ddl = f\"CREATE TABLE IF NOT EXISTS bronze.{dest} (\" + \", \".join(cols_sql) + \");\"\n"
        "    with engine_dwh.begin() as conn:\n"
        "        conn.execute(text(ddl))\n"
        "\n"
        "def get_next_snapshot_id(table_name):\n"
        "    with engine_dwh.connect() as conn:\n"
        "        return conn.execute(text(\"SELECT COALESCE(MAX(snapshot_id), 0) + 1 FROM bronze._load_control WHERE table_name = :t\"), {\"t\": table_name}).scalar()\n"
        "\n"
        "def get_last_snapshot(table_name):\n"
        "    try:\n"
        "        with engine_dwh.connect() as conn:\n"
        "            df = pd.read_sql(text(f\"SELECT * FROM bronze.{table_name} WHERE _snapshot_id = (SELECT MAX(_snapshot_id) FROM bronze.{table_name}) AND _change_op != 'DELETE'\"), conn)\n"
        "        meta_cols = [\"_snapshot_id\", \"_loaded_at\", \"_change_op\", \"_source\"]\n"
        "        return df.drop(columns=[c for c in meta_cols if c in df.columns])\n"
        "    except Exception:\n"
        "        return pd.DataFrame()\n"
        "\n"
        "def get_watermark(table_name):\n"
        "    \"\"\"Read the last successful watermark_date for an incremental table. Defaults to 1900-01-01.\"\"\"\n"
        "    try:\n"
        "        with engine_dwh.connect() as conn:\n"
        "            res = conn.execute(text(\"SELECT MAX(watermark_date) FROM bronze._load_control WHERE table_name = :t AND status = 'SUCCESS' AND watermark_date IS NOT NULL\"), {\"t\": table_name}).scalar()\n"
        "        return res if res is not None else date(1900, 1, 1)\n"
        "    except Exception:\n"
        "        return date(1900, 1, 1)\n"
        "\n"
        "def compute_row_hash(df, cols):\n"
        "    return df[cols].astype(str).apply(lambda row: hashlib.md5(\"|\".join(row).encode()).hexdigest(), axis=1)\n"
        "\n"
        "def diff_snapshots(df_new, df_prev, pk):\n"
        "    df_new = df_new.copy().set_index(pk)\n"
        "    if df_prev.empty:\n"
        "        res = df_new.reset_index()\n"
        "        res[\"_change_op\"] = \"INSERT\"\n"
        "        return res\n"
        "    df_prev = df_prev.copy().set_index(pk)\n"
        "    common_cols = [c for c in df_new.columns if c in df_prev.columns]\n"
        "    hash_new = compute_row_hash(df_new.reset_index(), pk + common_cols); hash_new.index = df_new.index\n"
        "    hash_prev = compute_row_hash(df_prev.reset_index(), pk + common_cols); hash_prev.index = df_prev.index\n"
        "    changed = []\n"
        "    new_keys = df_new.index.difference(df_prev.index)\n"
        "    if len(new_keys):\n"
        "        ins = df_new.loc[new_keys].reset_index(); ins[\"_change_op\"] = \"INSERT\"; changed.append(ins)\n"
        "    common_keys = df_new.index.intersection(df_prev.index)\n"
        "    updated_keys = common_keys[hash_new.loc[common_keys] != hash_prev.loc[common_keys]]\n"
        "    if len(updated_keys):\n"
        "        upd = df_new.loc[updated_keys].reset_index(); upd[\"_change_op\"] = \"UPDATE\"; changed.append(upd)\n"
        "    deleted_keys = df_prev.index.difference(df_new.index)\n"
        "    if len(deleted_keys):\n"
        "        dlt = df_prev.loc[deleted_keys].reset_index().reindex(columns=df_new.reset_index().columns)\n"
        "        dlt[\"_change_op\"] = \"DELETE\"; changed.append(dlt)\n"
        "    return pd.concat(changed, ignore_index=True) if changed else pd.DataFrame()\n"
        "\n"
        "def register_load(table_name, strategy, loaded_at, snapshot_id=None, watermark_date=None, rows_total=0, rows_inserted=0, rows_updated=0, rows_deleted=0, status=\"SUCCESS\"):\n"
        "    with engine_dwh.begin() as conn:\n"
        "        conn.execute(text(\"\"\"\n"
        "            INSERT INTO bronze._load_control (table_name, strategy, snapshot_id, watermark_date, loaded_at, rows_total, rows_inserted, rows_updated, rows_deleted, status)\n"
        "            VALUES (:tname, :strategy, :sid, :wm_date, :ts, :total, :inserted, :updated, :deleted, :status)\n"
        "        \"\"\"), {\"tname\": table_name, \"strategy\": strategy, \"sid\": snapshot_id, \"wm_date\": watermark_date, \"ts\": loaded_at, \"total\": rows_total, \"inserted\": rows_inserted, \"updated\": rows_updated, \"deleted\": rows_deleted, \"status\": status})\n"
    ))

    cells.append(md(
        "## 7. Save snapshots to local CSV (VPN ON)\n"
        "\n"
        "For each snapshot table: dump every column and write `tmp_snapshots/<table>.csv` plus the column-schema JSON in `tmp_snapshots/_schema/<table>.json`."
    ))
    cells.append(code(
        "tmp_dir = Path(\"tmp_snapshots\"); tmp_dir.mkdir(exist_ok=True)\n"
        "schema_dir = tmp_dir / \"_schema\"; schema_dir.mkdir(exist_ok=True)\n"
        "run_at = datetime.now(timezone.utc).replace(tzinfo=None)\n"
        "if 'engine_src' not in globals() or engine_src is None:\n"
        "    raise RuntimeError(\"engine_src missing — run cell '## 2. engine_src' (VPN ON).\")\n"
        "\n"
        "print(\"Saving source snapshots ...\")\n"
        "for t in SNAPSHOT_TABLES:\n"
        "    src, dest = t[\"src\"], t[\"dest\"]\n"
        "    try:\n"
        "        with engine_src.connect() as conn:\n"
        "            schema_df = pd.read_sql(text(\"\"\"\n"
        "                SELECT column_name, data_type, is_nullable\n"
        "                FROM information_schema.columns\n"
        "                WHERE table_schema='public' AND table_name=:t\n"
        "                ORDER BY ordinal_position\n"
        "            \"\"\"), conn, params={\"t\": src})\n"
        "        if schema_df.empty:\n"
        "            print(f\"⚠ {src}: source table not found, skipping.\")\n"
        "            continue\n"
        "        schema_entries = schema_df.to_dict(orient=\"records\")\n"
        "        (schema_dir / f\"{dest}.json\").write_text(json.dumps(schema_entries, indent=2), encoding=\"utf-8\")\n"
        "        cols_str = \", \".join([e[\"column_name\"] for e in schema_entries])\n"
        "        with engine_src.connect() as conn:\n"
        "            df_new = pd.read_sql(text(f\"SELECT {cols_str} FROM public.{src}\"), conn)\n"
        "        df_new.to_csv(tmp_dir / f\"{dest}.csv\", index=False)\n"
        "        print(f\"  {dest}: {len(df_new)} rows, {len(schema_entries)} cols → {tmp_dir / f'{dest}.csv'}\")\n"
        "    except Exception as e:\n"
        "        print(f\"  ✗ {dest}: {e}\")\n"
    ))

    cells.append(md(
        "## 8. Apply snapshots to DWH (VPN OFF)\n"
        "\n"
        "For each table: read CSV + schema JSON, ensure bronze table exists with correct DDL, diff against previous snapshot, append diff with metadata, register in `_load_control`."
    ))
    cells.append(code(
        "tmp_dir = Path(\"tmp_snapshots\"); schema_dir = tmp_dir / \"_schema\"\n"
        "run_at = datetime.now(timezone.utc).replace(tzinfo=None)\n"
        "if 'engine_dwh' not in globals() or engine_dwh is None:\n"
        "    raise RuntimeError(\"engine_dwh missing — run cell '## 3. engine_dwh' (VPN OFF).\")\n"
        "\n"
        "print(\"Applying snapshots to DWH...\")\n"
        "for t in SNAPSHOT_TABLES:\n"
        "    dest, pk = t[\"dest\"], t[\"pk\"]\n"
        "    csv_path = tmp_dir / f\"{dest}.csv\"\n"
        "    schema_path = schema_dir / f\"{dest}.json\"\n"
        "    if not csv_path.exists() or not schema_path.exists():\n"
        "        print(f\"  · {dest}: missing CSV or schema, skipping.\")\n"
        "        continue\n"
        "    try:\n"
        "        schema_entries = json.loads(schema_path.read_text(encoding=\"utf-8\"))\n"
        "        ensure_bronze_table(dest, schema_entries, SNAP_META_COLS)\n"
        "        df_new = pd.read_csv(csv_path)\n"
        "        df_prev = get_last_snapshot(dest)\n"
        "        df_diff = diff_snapshots(df_new, df_prev, pk)\n"
        "        n_total = len(df_new)\n"
        "        if df_diff.empty:\n"
        "            register_load(dest, \"snapshot\", run_at, rows_total=n_total)\n"
        "            print(f\"  · {dest}: no changes ({n_total} rows).\")\n"
        "            continue\n"
        "        snap_id = get_next_snapshot_id(dest)\n"
        "        df_diff[\"_snapshot_id\"] = snap_id\n"
        "        df_diff[\"_loaded_at\"] = run_at\n"
        "        df_diff[\"_source\"] = SRC_DB\n"
        "        with engine_dwh.connect() as conn:\n"
        "            target_cols = pd.read_sql(text(\"SELECT column_name FROM information_schema.columns WHERE table_schema='bronze' AND table_name=:t\"), conn, params={\"t\": dest})[\"column_name\"].tolist()\n"
        "        df_diff = df_diff[[c for c in df_diff.columns if c in target_cols]]\n"
        "        with engine_dwh.begin() as conn:\n"
        "            df_diff.to_sql(dest, conn, schema=\"bronze\", if_exists=\"append\", index=False)\n"
        "        i = int((df_diff[\"_change_op\"] == \"INSERT\").sum())\n"
        "        u = int((df_diff[\"_change_op\"] == \"UPDATE\").sum())\n"
        "        d = int((df_diff[\"_change_op\"] == \"DELETE\").sum())\n"
        "        register_load(dest, \"snapshot\", run_at, snapshot_id=snap_id, rows_total=n_total, rows_inserted=i, rows_updated=u, rows_deleted=d)\n"
        "        print(f\"  · {dest}: ins={i}, upd={u}, del={d} (snap {snap_id}).\")\n"
        "    except Exception as e:\n"
        "        register_load(dest, \"snapshot\", run_at, status=\"ERROR\")\n"
        "        print(f\"  ✗ {dest}: {e}\")\n"
    ))

    cells.append(md(
        "## 9. Save incremental extracts (VPN ON)\n"
        "\n"
        "Reads `bronze._load_control` watermark first (this needs the DWH, so we **also** open `engine_dwh` here for read-only access — VPN OFF). If you cannot reach the DWH right now, the watermark falls back to `1900-01-01` and the extract becomes a full load.\n"
        "\n"
        "**Recommended flow:** run this cell with VPN OFF first to capture the watermark in a Python variable, then run with VPN ON to extract."
    ))
    cells.append(code(
        "tmp_incr = Path(\"tmp_increments\"); tmp_incr.mkdir(exist_ok=True)\n"
        "schema_dir_incr = tmp_incr / \"_schema\"; schema_dir_incr.mkdir(exist_ok=True)\n"
        "run_at = datetime.now(timezone.utc).replace(tzinfo=None)\n"
        "\n"
        "if 'engine_src' not in globals() or engine_src is None:\n"
        "    raise RuntimeError(\"engine_src missing — run cell '## 2. engine_src' (VPN ON).\")\n"
        "\n"
        "wm_invoices = get_watermark(\"invoices\") if 'engine_dwh' in globals() and engine_dwh is not None else date(1900, 1, 1)\n"
        "print(f\"Watermark for invoices: {wm_invoices}\")\n"
        "\n"
        "# 1) Source schema for invoices\n"
        "with engine_src.connect() as conn:\n"
        "    inv_schema = pd.read_sql(text(\"SELECT column_name, data_type, is_nullable FROM information_schema.columns WHERE table_schema='public' AND table_name='invoices' ORDER BY ordinal_position\"), conn).to_dict(orient=\"records\")\n"
        "    line_schema = pd.read_sql(text(\"SELECT column_name, data_type, is_nullable FROM information_schema.columns WHERE table_schema='public' AND table_name='invoicelines' ORDER BY ordinal_position\"), conn).to_dict(orient=\"records\")\n"
        "(schema_dir_incr / \"invoices.json\").write_text(json.dumps(inv_schema, indent=2), encoding=\"utf-8\")\n"
        "(schema_dir_incr / \"invoicelines.json\").write_text(json.dumps(line_schema, indent=2), encoding=\"utf-8\")\n"
        "\n"
        "# 2) Invoices: full columns since watermark\n"
        "inv_cols = \", \".join([e[\"column_name\"] for e in inv_schema])\n"
        "with engine_src.connect() as conn:\n"
        "    df_inv = pd.read_sql(text(f\"SELECT {inv_cols} FROM public.invoices WHERE invoicedate > :wm ORDER BY invoicedate\"), conn, params={\"wm\": wm_invoices})\n"
        "df_inv.to_csv(tmp_incr / \"invoices.csv\", index=False)\n"
        "print(f\"  invoices: {len(df_inv)} rows since {wm_invoices}\")\n"
        "\n"
        "# 3) Invoicelines for the new invoices\n"
        "if not df_inv.empty:\n"
        "    line_cols = \", \".join([e[\"column_name\"] for e in line_schema])\n"
        "    new_ids = df_inv[\"invoiceid\"].tolist()\n"
        "    with engine_src.connect() as conn:\n"
        "        df_lines = pd.read_sql(text(f\"SELECT {line_cols} FROM public.invoicelines WHERE invoiceid = ANY(:ids)\"), conn, params={\"ids\": new_ids})\n"
        "    df_lines.to_csv(tmp_incr / \"invoicelines.csv\", index=False)\n"
        "    print(f\"  invoicelines: {len(df_lines)} rows\")\n"
        "else:\n"
        "    pd.DataFrame().to_csv(tmp_incr / \"invoicelines.csv\", index=False)\n"
        "    print(\"  invoicelines: 0 rows (no new invoices)\")\n"
    ))

    cells.append(md(
        "## 10. Apply incremental CSVs to DWH (VPN OFF)"
    ))
    cells.append(code(
        "tmp_incr = Path(\"tmp_increments\"); schema_dir_incr = tmp_incr / \"_schema\"\n"
        "run_at = datetime.now(timezone.utc).replace(tzinfo=None)\n"
        "if 'engine_dwh' not in globals() or engine_dwh is None:\n"
        "    raise RuntimeError(\"engine_dwh missing — run cell '## 3. engine_dwh' (VPN OFF).\")\n"
        "\n"
        "print(\"Applying incremental CSVs to DWH...\")\n"
        "for t in DATE_TABLES:\n"
        "    dest, pk = t[\"dest\"], t[\"pk\"]\n"
        "    csv_path = tmp_incr / f\"{dest}.csv\"\n"
        "    schema_path = schema_dir_incr / f\"{dest}.json\"\n"
        "    if not csv_path.exists() or not schema_path.exists():\n"
        "        print(f\"  · {dest}: missing CSV or schema, skipping.\")\n"
        "        continue\n"
        "    try:\n"
        "        schema_entries = json.loads(schema_path.read_text(encoding=\"utf-8\"))\n"
        "        ensure_bronze_table(dest, schema_entries, DATE_META_COLS)\n"
        "        df_new = pd.read_csv(csv_path)\n"
        "        if df_new.empty:\n"
        "            register_load(dest, \"incremental\", run_at, rows_total=0)\n"
        "            print(f\"  · {dest}: empty CSV, nothing to load.\")\n"
        "            continue\n"
        "        df_new[\"_loaded_at\"] = run_at\n"
        "        df_new[\"_source\"] = SRC_DB\n"
        "        with engine_dwh.connect() as conn:\n"
        "            target_cols = pd.read_sql(text(\"SELECT column_name FROM information_schema.columns WHERE table_schema='bronze' AND table_name=:t\"), conn, params={\"t\": dest})[\"column_name\"].tolist()\n"
        "        df_to_load = df_new[[c for c in df_new.columns if c in target_cols]]\n"
        "        with engine_dwh.begin() as conn:\n"
        "            df_to_load.to_sql(dest, conn, schema=\"bronze\", if_exists=\"append\", index=False)\n"
        "        wm_date = None\n"
        "        if t[\"watermark\"] in df_new.columns:\n"
        "            try:\n"
        "                wm_date = pd.to_datetime(df_new[t[\"watermark\"]]).max().date()\n"
        "            except Exception:\n"
        "                wm_date = None\n"
        "        register_load(dest, \"incremental\", run_at, watermark_date=wm_date, rows_total=len(df_new), rows_inserted=len(df_new))\n"
        "        print(f\"  · {dest}: {len(df_new)} rows loaded (watermark: {wm_date}).\")\n"
        "    except Exception as e:\n"
        "        register_load(dest, \"incremental\", run_at, status=\"ERROR\")\n"
        "        print(f\"  ✗ {dest}: {e}\")\n"
    ))

    nb["cells"] = cells
    nb_path.write_text(json.dumps(nb, indent=1, ensure_ascii=False), encoding="utf-8")
    print(f"Patched {nb_path.name}: {len(cells)} cells")


# ===================== 02_silver.ipynb =====================
def patch_silver():
    nb_path = ROOT / "02_silver.ipynb"
    nb = json.loads(nb_path.read_text(encoding="utf-8"))
    cells = []

    cells.append(md(
        "# 02 · Silver — Cleansing and conformed staging\n"
        "\n"
        "Reads from `bronze.*` (active snapshot only) and writes `silver.stg_*` tables. Operates only on `engine_dwh` (VPN OFF)."
    ))

    cells.append(md(
        "## 1. Imports and engine"
    ))
    cells.append(code(
        "import pandas as pd\n"
        "from datetime import datetime, timezone\n"
        "from sqlalchemy import create_engine, text\n"
        "from sqlalchemy.engine import URL\n"
        "from dotenv import load_dotenv\n"
        "import os\n"
        "\n"
        "load_dotenv(override=True)\n"
        "\n"
        "SUPABASE_URL  = os.getenv(\"SUPABASE_URL\")\n"
        "SUPABASE_PORT = int(os.getenv(\"SUPABASE_PORT\", 5432))\n"
        "SUPABASE_DB   = os.getenv(\"SUPABASE_DB\")\n"
        "SUPABASE_USER = os.getenv(\"SUPABASE_USER\")\n"
        "SUPABASE_PASSWORD = os.getenv(\"SUPABASE_PASSWORD\")\n"
        "\n"
        "def make_engine(host, port, db, user, password, sslmode=None):\n"
        "    return create_engine(URL.create(\"postgresql+psycopg2\", username=user, password=password, host=host, port=port, database=db, query={\"sslmode\": sslmode} if sslmode else None))\n"
        "\n"
        "if not all([SUPABASE_URL, SUPABASE_DB, SUPABASE_USER, SUPABASE_PASSWORD]):\n"
        "    raise ValueError(\"SUPABASE env vars missing\")\n"
        "engine_dwh = make_engine(SUPABASE_URL, SUPABASE_PORT, SUPABASE_DB, SUPABASE_USER, SUPABASE_PASSWORD, sslmode=\"require\")\n"
        "run_at = datetime.now(timezone.utc).replace(tzinfo=None)\n"
        "print(\"✓ engine_dwh ready.\")\n"
    ))

    cells.append(md(
        "## 2. DDL — silver staging tables (drop and recreate)\n"
        "\n"
        "Silver is non-historized — every run rebuilds the staging tables. Idempotent."
    ))
    cells.append(code(
        "DDL_SILVER = {\n"
        "    \"stg_employees\": \"\"\"\n"
        "        CREATE TABLE IF NOT EXISTS silver.stg_employees (\n"
        "            personid INT NOT NULL,\n"
        "            fullname TEXT,\n"
        "            issalesperson INT,\n"
        "            _loaded_at TIMESTAMP NOT NULL,\n"
        "            _source_snapshot INT NOT NULL\n"
        "        );\n"
        "    \"\"\",\n"
        "    \"stg_customers\": \"\"\"\n"
        "        CREATE TABLE IF NOT EXISTS silver.stg_customers (\n"
        "            customerid INT NOT NULL,\n"
        "            customername TEXT,\n"
        "            category TEXT,\n"
        "            deliverycityid INT,\n"
        "            _loaded_at TIMESTAMP NOT NULL,\n"
        "            _source_snapshot INT NOT NULL\n"
        "        );\n"
        "    \"\"\",\n"
        "    \"stg_locations\": \"\"\"\n"
        "        CREATE TABLE IF NOT EXISTS silver.stg_locations (\n"
        "            locationid INT NOT NULL,\n"
        "            city TEXT,\n"
        "            state TEXT,\n"
        "            country TEXT,\n"
        "            salesterritory TEXT,\n"
        "            _loaded_at TIMESTAMP NOT NULL,\n"
        "            _source_snapshot INT NOT NULL\n"
        "        );\n"
        "    \"\"\",\n"
        "    \"stg_products\": \"\"\"\n"
        "        CREATE TABLE IF NOT EXISTS silver.stg_products (\n"
        "            stockitemid INT NOT NULL,\n"
        "            stockitemname TEXT,\n"
        "            brand TEXT,\n"
        "            _loaded_at TIMESTAMP NOT NULL,\n"
        "            _source_snapshot INT NOT NULL\n"
        "        );\n"
        "    \"\"\",\n"
        "    \"stg_deliverymethods\": \"\"\"\n"
        "        CREATE TABLE IF NOT EXISTS silver.stg_deliverymethods (\n"
        "            deliverymethodid INT NOT NULL,\n"
        "            deliverymethodname TEXT,\n"
        "            _loaded_at TIMESTAMP NOT NULL,\n"
        "            _source_snapshot INT NOT NULL\n"
        "        );\n"
        "    \"\"\",\n"
        "    \"stg_paymentmethods\": \"\"\"\n"
        "        CREATE TABLE IF NOT EXISTS silver.stg_paymentmethods (\n"
        "            paymentmethodid INT NOT NULL,\n"
        "            paymentmethodname TEXT,\n"
        "            _loaded_at TIMESTAMP NOT NULL,\n"
        "            _source_snapshot INT NOT NULL\n"
        "        );\n"
        "    \"\"\",\n"
        "    \"stg_transactiontypes\": \"\"\"\n"
        "        CREATE TABLE IF NOT EXISTS silver.stg_transactiontypes (\n"
        "            transactiontypeid INT NOT NULL,\n"
        "            transactiontypename TEXT,\n"
        "            _loaded_at TIMESTAMP NOT NULL,\n"
        "            _source_snapshot INT NOT NULL\n"
        "        );\n"
        "    \"\"\",\n"
        "    \"stg_fact_sales\": \"\"\"\n"
        "        CREATE TABLE IF NOT EXISTS silver.stg_fact_sales (\n"
        "            saleskey INT NOT NULL,\n"
        "            invoiceid INT NOT NULL,\n"
        "            invoicedate DATE,\n"
        "            salespersonpersonid INT,\n"
        "            accountspersonid INT,\n"
        "            customerid INT,\n"
        "            stockitemid INT,\n"
        "            deliverycityid INT,\n"
        "            deliverymethodid INT,\n"
        "            quantity INT,\n"
        "            unitprice NUMERIC,\n"
        "            taxamount NUMERIC,\n"
        "            extendedprice NUMERIC,\n"
        "            lineprofit NUMERIC,\n"
        "            _loaded_at TIMESTAMP NOT NULL\n"
        "        );\n"
        "    \"\"\",\n"
        "    \"stg_fact_invoices\": \"\"\"\n"
        "        CREATE TABLE IF NOT EXISTS silver.stg_fact_invoices (\n"
        "            invoiceid INT NOT NULL,\n"
        "            invoicedate DATE,\n"
        "            salespersonpersonid INT,\n"
        "            accountspersonid INT,\n"
        "            customerid INT,\n"
        "            deliverycityid INT,\n"
        "            deliverymethodid INT,\n"
        "            invoiceamount NUMERIC,\n"
        "            paymentdelay_days INT,\n"
        "            outstandingbalance NUMERIC,\n"
        "            _loaded_at TIMESTAMP NOT NULL\n"
        "        );\n"
        "    \"\"\",\n"
        "}\n"
        "\n"
        "with engine_dwh.begin() as conn:\n"
        "    for name, ddl in DDL_SILVER.items():\n"
        "        conn.execute(text(f\"DROP TABLE IF EXISTS silver.{name} CASCADE\"))\n"
        "        conn.execute(text(ddl))\n"
        "print(\"✓ Silver staging tables (re)created.\")\n"
    ))

    cells.append(md(
        "## 3. Helper functions"
    ))
    cells.append(code(
        "def read_active_snapshot(table_name):\n"
        "    sql = f\"SELECT * FROM bronze.{table_name} WHERE _snapshot_id = (SELECT MAX(_snapshot_id) FROM bronze.{table_name}) AND _change_op != 'DELETE'\"\n"
        "    with engine_dwh.connect() as conn:\n"
        "        return pd.read_sql(text(sql), conn)\n"
        "\n"
        "def clean_str(s):\n"
        "    \"\"\"Strip whitespace and convert empty strings to NaN. Tolerates non-string inputs.\"\"\"\n"
        "    return s.astype(\"string\").str.strip().replace({\"\": pd.NA})\n"
    ))

    cells.append(md(
        "## 4. stg_employees"
    ))
    cells.append(code(
        "print(\"Processing stg_employees...\")\n"
        "df_people = read_active_snapshot(\"people\")\n"
        "if not df_people.empty:\n"
        "    snap_id = int(df_people[\"_snapshot_id\"].max())\n"
        "    out = pd.DataFrame({\n"
        "        \"personid\": df_people[\"personid\"],\n"
        "        \"fullname\": clean_str(df_people[\"fullname\"]),\n"
        "        \"issalesperson\": df_people[\"issalesperson\"],\n"
        "        \"_loaded_at\": run_at,\n"
        "        \"_source_snapshot\": snap_id,\n"
        "    })\n"
        "    with engine_dwh.begin() as conn:\n"
        "        out.to_sql(\"stg_employees\", conn, schema=\"silver\", if_exists=\"append\", index=False)\n"
        "    print(f\"  stg_employees: {len(out)} records\")\n"
        "else:\n"
        "    print(\"  stg_employees: no source data\")\n"
    ))

    cells.append(md(
        "## 5. stg_customers"
    ))
    cells.append(code(
        "print(\"Processing stg_customers...\")\n"
        "df_cust = read_active_snapshot(\"customers\")\n"
        "df_cat = read_active_snapshot(\"customercategories\")\n"
        "if not df_cust.empty:\n"
        "    snap_id = int(df_cust[\"_snapshot_id\"].max())\n"
        "    df = df_cust.merge(df_cat[[\"customercategoryid\", \"customercategoryname\"]], on=\"customercategoryid\", how=\"left\")\n"
        "    out = pd.DataFrame({\n"
        "        \"customerid\": df[\"customerid\"],\n"
        "        \"customername\": clean_str(df[\"customername\"]),\n"
        "        \"category\": clean_str(df[\"customercategoryname\"]),\n"
        "        \"deliverycityid\": df[\"deliverycityid\"],\n"
        "        \"_loaded_at\": run_at,\n"
        "        \"_source_snapshot\": snap_id,\n"
        "    })\n"
        "    with engine_dwh.begin() as conn:\n"
        "        out.to_sql(\"stg_customers\", conn, schema=\"silver\", if_exists=\"append\", index=False)\n"
        "    print(f\"  stg_customers: {len(out)} records\")\n"
        "else:\n"
        "    print(\"  stg_customers: no source data\")\n"
    ))

    cells.append(md(
        "## 6. stg_locations"
    ))
    cells.append(code(
        "print(\"Processing stg_locations...\")\n"
        "df_cities = read_active_snapshot(\"cities\")\n"
        "df_states = read_active_snapshot(\"stateprovinces\")\n"
        "df_countries = read_active_snapshot(\"countries\")\n"
        "if not df_cities.empty:\n"
        "    snap_id = int(df_cities[\"_snapshot_id\"].max())\n"
        "    df = (df_cities.merge(df_states[[\"stateprovinceid\", \"stateprovincename\", \"countryid\", \"salesterritory\"]], on=\"stateprovinceid\", how=\"left\")\n"
        "                    .merge(df_countries[[\"countryid\", \"countryname\"]], on=\"countryid\", how=\"left\"))\n"
        "    out = pd.DataFrame({\n"
        "        \"locationid\": df[\"cityid\"],\n"
        "        \"city\": clean_str(df[\"cityname\"]),\n"
        "        \"state\": clean_str(df[\"stateprovincename\"]),\n"
        "        \"country\": clean_str(df[\"countryname\"]),\n"
        "        \"salesterritory\": clean_str(df[\"salesterritory\"]),\n"
        "        \"_loaded_at\": run_at,\n"
        "        \"_source_snapshot\": snap_id,\n"
        "    })\n"
        "    with engine_dwh.begin() as conn:\n"
        "        out.to_sql(\"stg_locations\", conn, schema=\"silver\", if_exists=\"append\", index=False)\n"
        "    print(f\"  stg_locations: {len(out)} records\")\n"
        "else:\n"
        "    print(\"  stg_locations: no source data\")\n"
    ))

    cells.append(md(
        "## 7. stg_products"
    ))
    cells.append(code(
        "print(\"Processing stg_products...\")\n"
        "df_prod = read_active_snapshot(\"stockitems\")\n"
        "if not df_prod.empty:\n"
        "    out = pd.DataFrame({\n"
        "        \"stockitemid\": df_prod[\"stockitemid\"],\n"
        "        \"stockitemname\": clean_str(df_prod[\"stockitemname\"]),\n"
        "        \"brand\": clean_str(df_prod[\"brand\"]),\n"
        "        \"_loaded_at\": run_at,\n"
        "        \"_source_snapshot\": int(df_prod[\"_snapshot_id\"].max()),\n"
        "    })\n"
        "    with engine_dwh.begin() as conn:\n"
        "        out.to_sql(\"stg_products\", conn, schema=\"silver\", if_exists=\"append\", index=False)\n"
        "    print(f\"  stg_products: {len(out)} records\")\n"
        "else:\n"
        "    print(\"  stg_products: no source data\")\n"
    ))

    cells.append(md(
        "## 8. stg_deliverymethods / stg_paymentmethods / stg_transactiontypes"
    ))
    cells.append(code(
        "for src_table, stg_table, key_col, name_col in [\n"
        "    (\"deliverymethods\", \"stg_deliverymethods\", \"deliverymethodid\", \"deliverymethodname\"),\n"
        "    (\"paymentmethods\", \"stg_paymentmethods\", \"paymentmethodid\", \"paymentmethodname\"),\n"
        "    (\"transactiontypes\", \"stg_transactiontypes\", \"transactiontypeid\", \"transactiontypename\"),\n"
        "]:\n"
        "    print(f\"Processing {stg_table}...\")\n"
        "    try:\n"
        "        df = read_active_snapshot(src_table)\n"
        "    except Exception as e:\n"
        "        print(f\"  ✗ {stg_table}: {e}\")\n"
        "        continue\n"
        "    if df.empty:\n"
        "        print(f\"  {stg_table}: no source data\")\n"
        "        continue\n"
        "    out = pd.DataFrame({\n"
        "        key_col: df[key_col],\n"
        "        name_col: clean_str(df[name_col]),\n"
        "        \"_loaded_at\": run_at,\n"
        "        \"_source_snapshot\": int(df[\"_snapshot_id\"].max()),\n"
        "    })\n"
        "    with engine_dwh.begin() as conn:\n"
        "        out.to_sql(stg_table, conn, schema=\"silver\", if_exists=\"append\", index=False)\n"
        "    print(f\"  {stg_table}: {len(out)} records\")\n"
    ))

    cells.append(md(
        "## 9. stg_fact_sales and stg_fact_invoices\n"
        "\n"
        "Joins:\n"
        "- `bronze.invoicelines` ⨝ `bronze.invoices` (header info: salesperson, accounts person, customer, delivery method)\n"
        "- ⨝ `bronze.customers` (delivery city → location)\n"
        "- For invoice header: aggregate invoicelines for `invoiceamount`; left-join `bronze.customertransactions` for `paymentdelay_days` and `outstandingbalance`."
    ))
    cells.append(code(
        "print(\"Processing stg_fact_sales & stg_fact_invoices...\")\n"
        "with engine_dwh.connect() as conn:\n"
        "    df_inv = pd.read_sql(text(\"SELECT * FROM bronze.invoices\"), conn)\n"
        "    df_lines = pd.read_sql(text(\"SELECT * FROM bronze.invoicelines\"), conn)\n"
        "df_cust = read_active_snapshot(\"customers\")\n"
        "try:\n"
        "    df_trans = read_active_snapshot(\"customertransactions\")\n"
        "except Exception:\n"
        "    df_trans = pd.DataFrame()\n"
        "\n"
        "if df_inv.empty or df_lines.empty:\n"
        "    print(\"  No invoices/invoicelines in bronze. Skipping facts.\")\n"
        "else:\n"
        "    inv_cols = [\"invoiceid\", \"invoicedate\", \"salespersonpersonid\", \"accountspersonid\", \"customerid\"]\n"
        "    if \"deliverymethodid\" in df_inv.columns:\n"
        "        inv_cols.append(\"deliverymethodid\")\n"
        "    df_sales = (df_lines.merge(df_inv[inv_cols], on=\"invoiceid\", how=\"left\")\n"
        "                       .merge(df_cust[[\"customerid\", \"deliverycityid\"]], on=\"customerid\", how=\"left\"))\n"
        "\n"
        "    stg_fact_sales = pd.DataFrame({\n"
        "        \"saleskey\": df_sales[\"invoicelineid\"],\n"
        "        \"invoiceid\": df_sales[\"invoiceid\"],\n"
        "        \"invoicedate\": pd.to_datetime(df_sales[\"invoicedate\"]),\n"
        "        \"salespersonpersonid\": df_sales[\"salespersonpersonid\"],\n"
        "        \"accountspersonid\": df_sales[\"accountspersonid\"],\n"
        "        \"customerid\": df_sales[\"customerid\"],\n"
        "        \"stockitemid\": df_sales[\"stockitemid\"],\n"
        "        \"deliverycityid\": df_sales[\"deliverycityid\"],\n"
        "        \"deliverymethodid\": df_sales[\"deliverymethodid\"] if \"deliverymethodid\" in df_sales.columns else None,\n"
        "        \"quantity\": df_sales[\"quantity\"],\n"
        "        \"unitprice\": df_sales[\"unitprice\"],\n"
        "        \"taxamount\": df_sales[\"taxamount\"],\n"
        "        \"extendedprice\": df_sales[\"extendedprice\"],\n"
        "        \"lineprofit\": df_sales[\"lineprofit\"],\n"
        "        \"_loaded_at\": run_at,\n"
        "    })\n"
        "\n"
        "    df_header = df_inv.merge(df_cust[[\"customerid\", \"deliverycityid\"]], on=\"customerid\", how=\"left\")\n"
        "    invoice_amounts = df_lines.groupby(\"invoiceid\")[\"extendedprice\"].sum().reset_index().rename(columns={\"extendedprice\": \"invoiceamount\"})\n"
        "    df_header = df_header.merge(invoice_amounts, on=\"invoiceid\", how=\"left\")\n"
        "\n"
        "    if not df_trans.empty:\n"
        "        trans = df_trans.groupby(\"invoiceid\").agg({\n"
        "            \"outstandingbalance\": \"sum\",\n"
        "            \"finalizationdate\": \"max\",\n"
        "            \"transactiondate\": \"min\",\n"
        "        }).reset_index()\n"
        "        df_header = df_header.merge(trans, on=\"invoiceid\", how=\"left\")\n"
        "        df_header[\"paymentdelay_days\"] = (pd.to_datetime(df_header[\"finalizationdate\"]) - pd.to_datetime(df_header[\"invoicedate\"])).dt.days\n"
        "        df_header[\"paymentdelay_days\"] = df_header[\"paymentdelay_days\"].fillna(0).astype(int)\n"
        "        df_header[\"outstandingbalance\"] = df_header[\"outstandingbalance\"].fillna(0)\n"
        "    else:\n"
        "        df_header[\"paymentdelay_days\"] = 0\n"
        "        df_header[\"outstandingbalance\"] = 0\n"
        "\n"
        "    stg_fact_invoices = pd.DataFrame({\n"
        "        \"invoiceid\": df_header[\"invoiceid\"],\n"
        "        \"invoicedate\": pd.to_datetime(df_header[\"invoicedate\"]),\n"
        "        \"salespersonpersonid\": df_header[\"salespersonpersonid\"],\n"
        "        \"accountspersonid\": df_header[\"accountspersonid\"],\n"
        "        \"customerid\": df_header[\"customerid\"],\n"
        "        \"deliverycityid\": df_header[\"deliverycityid\"],\n"
        "        \"deliverymethodid\": df_header[\"deliverymethodid\"] if \"deliverymethodid\" in df_header.columns else None,\n"
        "        \"invoiceamount\": df_header[\"invoiceamount\"],\n"
        "        \"paymentdelay_days\": df_header[\"paymentdelay_days\"],\n"
        "        \"outstandingbalance\": df_header[\"outstandingbalance\"],\n"
        "        \"_loaded_at\": run_at,\n"
        "    })\n"
        "\n"
        "    with engine_dwh.begin() as conn:\n"
        "        stg_fact_sales.to_sql(\"stg_fact_sales\", conn, schema=\"silver\", if_exists=\"append\", index=False)\n"
        "        stg_fact_invoices.to_sql(\"stg_fact_invoices\", conn, schema=\"silver\", if_exists=\"append\", index=False)\n"
        "    print(f\"  stg_fact_sales: {len(stg_fact_sales)} records\")\n"
        "    print(f\"  stg_fact_invoices: {len(stg_fact_invoices)} records\")\n"
    ))

    nb["cells"] = cells
    nb_path.write_text(json.dumps(nb, indent=1, ensure_ascii=False), encoding="utf-8")
    print(f"Patched {nb_path.name}: {len(cells)} cells")


# ===================== 03_gold.ipynb =====================
def patch_gold():
    nb_path = ROOT / "03_gold.ipynb"
    nb = json.loads(nb_path.read_text(encoding="utf-8"))
    cells = []

    cells.append(md(
        "# 03 · Gold — Star schema (SCD2 dims + facts)\n"
        "\n"
        "Operates on `engine_dwh` only (VPN OFF). Reads from `silver.*`, writes to `gold.*`."
    ))

    cells.append(md(
        "## 1. Imports and engine"
    ))
    cells.append(code(
        "import pandas as pd\n"
        "import hashlib\n"
        "from datetime import date, datetime, timezone, timedelta\n"
        "from sqlalchemy import create_engine, text\n"
        "from sqlalchemy.engine import URL\n"
        "from dotenv import load_dotenv\n"
        "import os\n"
        "\n"
        "load_dotenv(override=True)\n"
        "\n"
        "SUPABASE_URL  = os.getenv(\"SUPABASE_URL\")\n"
        "SUPABASE_PORT = int(os.getenv(\"SUPABASE_PORT\", 5432))\n"
        "SUPABASE_DB   = os.getenv(\"SUPABASE_DB\")\n"
        "SUPABASE_USER = os.getenv(\"SUPABASE_USER\")\n"
        "SUPABASE_PASSWORD = os.getenv(\"SUPABASE_PASSWORD\")\n"
        "\n"
        "def make_engine(host, port, db, user, password, sslmode=None):\n"
        "    return create_engine(URL.create(\"postgresql+psycopg2\", username=user, password=password, host=host, port=port, database=db, query={\"sslmode\": sslmode} if sslmode else None))\n"
        "\n"
        "if not all([SUPABASE_URL, SUPABASE_DB, SUPABASE_USER, SUPABASE_PASSWORD]):\n"
        "    raise ValueError(\"SUPABASE env vars missing\")\n"
        "engine = make_engine(SUPABASE_URL, SUPABASE_PORT, SUPABASE_DB, SUPABASE_USER, SUPABASE_PASSWORD, sslmode=\"require\")\n"
        "run_at = datetime.now(timezone.utc).replace(tzinfo=None)\n"
        "print(\"✓ engine ready.\")\n"
    ))

    cells.append(md(
        "## 2. SCD Type 2 helpers"
    ))
    cells.append(code(
        "def row_hash(df, cols):\n"
        "    def hash_row(row):\n"
        "        parts = [\"\" if pd.isna(v) else str(v) for v in row]\n"
        "        return hashlib.md5(\"|\".join(parts).encode()).hexdigest()\n"
        "    return df[cols].apply(hash_row, axis=1)\n"
        "\n"
        "def _insert_rows(df, gold_table, surrogate_key):\n"
        "    cols = [c for c in df.columns if c != surrogate_key and not c.startswith(\"_\")]\n"
        "    with engine.begin() as conn:\n"
        "        df[cols].where(pd.notna(df[cols]), None).to_sql(gold_table, conn, schema=\"gold\", if_exists=\"append\", index=False)\n"
        "\n"
        "def load_scd2(df_silver, gold_table, surrogate_key, business_key, attribute_cols, effective_date):\n"
        "    gold_table_lower = gold_table.lower()\n"
        "    with engine.connect() as conn:\n"
        "        try:\n"
        "            df_gold = pd.read_sql(text(f\"SELECT * FROM gold.{gold_table_lower} WHERE date_to IS NULL\"), conn)\n"
        "        except Exception:\n"
        "            df_gold = pd.DataFrame()\n"
        "    n_inserted = 0; n_updated = 0\n"
        "    silver_keys = set(df_silver[business_key].dropna().tolist())\n"
        "    hash_silver = row_hash(df_silver, attribute_cols); hash_silver.index = df_silver[business_key].values\n"
        "    if not df_gold.empty:\n"
        "        gold_keys = set(df_gold[business_key].dropna().tolist())\n"
        "        common_attr = [c for c in attribute_cols if c in df_gold.columns]\n"
        "        hash_gold = row_hash(df_gold, common_attr); hash_gold.index = df_gold[business_key].values\n"
        "    else:\n"
        "        gold_keys = set(); hash_gold = pd.Series(dtype=str)\n"
        "    new_keys = silver_keys - gold_keys\n"
        "    if new_keys:\n"
        "        df_new = df_silver[df_silver[business_key].isin(new_keys)].copy()\n"
        "        df_new[\"version\"] = 1; df_new[\"date_from\"] = effective_date; df_new[\"date_to\"] = None\n"
        "        _insert_rows(df_new, gold_table_lower, surrogate_key)\n"
        "        n_inserted = len(df_new)\n"
        "    common_keys = silver_keys & gold_keys\n"
        "    changed_keys = {k for k in common_keys if hash_silver.get(k) != hash_gold.get(k)}\n"
        "    if changed_keys:\n"
        "        keys_list = list(changed_keys)\n"
        "        with engine.begin() as conn:\n"
        "            conn.execute(text(f\"UPDATE gold.{gold_table_lower} SET date_to = :dt WHERE {business_key} = ANY(:keys) AND date_to IS NULL\"), {\"dt\": effective_date, \"keys\": keys_list})\n"
        "        df_upd = df_silver[df_silver[business_key].isin(changed_keys)].copy()\n"
        "        df_upd[\"version\"] = df_upd[business_key].map(df_gold.set_index(business_key)[\"version\"]) + 1\n"
        "        df_upd[\"date_from\"] = effective_date; df_upd[\"date_to\"] = None\n"
        "        _insert_rows(df_upd, gold_table_lower, surrogate_key)\n"
        "        n_updated = len(df_upd)\n"
        "    return {\"inserted\": n_inserted, \"updated\": n_updated}\n"
    ))

    cells.append(md(
        "## 3. DimDate"
    ))
    cells.append(code(
        "with engine.connect() as conn:\n"
        "    row = conn.execute(text(\"SELECT MIN(invoicedate), MAX(invoicedate) FROM silver.stg_fact_invoices\")).fetchone()\n"
        "if row and row[0]:\n"
        "    date_start = date(row[0].year, 1, 1); date_end = date(row[1].year, 12, 31)\n"
        "else:\n"
        "    date_start = date(2013, 1, 1); date_end = date(2016, 12, 31)\n"
        "records = []\n"
        "current = date_start\n"
        "while current <= date_end:\n"
        "    records.append({\"datekey\": int(current.strftime(\"%Y%m%d\")), \"date\": current,\n"
        "                    \"year\": current.year, \"month\": current.month, \"day\": current.day})\n"
        "    current += timedelta(days=1)\n"
        "df_date = pd.DataFrame(records)\n"
        "with engine.begin() as conn:\n"
        "    conn.execute(text(\"TRUNCATE TABLE gold.dimdate CASCADE\"))\n"
        "    df_date.to_sql(\"dimdate\", conn, schema=\"gold\", if_exists=\"append\", index=False)\n"
        "print(f\"✓ dimdate populated: {len(df_date)} days from {date_start} to {date_end}.\")\n"
    ))

    cells.append(md(
        "## 4. SCD2 dimensions"
    ))
    cells.append(code(
        "with engine.connect() as conn:\n"
        "    df_emp  = pd.read_sql(text(\"SELECT personid, fullname, issalesperson FROM silver.stg_employees\"), conn)\n"
        "    df_cust = pd.read_sql(text(\"SELECT customerid, customername, category FROM silver.stg_customers\"), conn)\n"
        "    df_loc  = pd.read_sql(text(\"SELECT locationid, city, state, country, salesterritory FROM silver.stg_locations\"), conn)\n"
        "    df_prod = pd.read_sql(text(\"SELECT stockitemid, stockitemname, brand FROM silver.stg_products\"), conn)\n"
        "    df_dm   = pd.read_sql(text(\"SELECT deliverymethodid, deliverymethodname FROM silver.stg_deliverymethods\"), conn)\n"
        "    df_pm   = pd.read_sql(text(\"SELECT paymentmethodid, paymentmethodname FROM silver.stg_paymentmethods\"), conn)\n"
        "\n"
        "s1 = load_scd2(df_emp,  \"dimemployee\",       \"employeekey\",       \"personid\",         [\"fullname\", \"issalesperson\"], run_at)\n"
        "s2 = load_scd2(df_cust, \"dimcustomer\",       \"customerkey\",       \"customerid\",       [\"customername\", \"category\"], run_at)\n"
        "s3 = load_scd2(df_loc,  \"dimlocation\",       \"locationkey\",       \"locationid\",       [\"city\", \"state\", \"country\", \"salesterritory\"], run_at)\n"
        "s4 = load_scd2(df_prod, \"dimproduct\",        \"productkey\",        \"stockitemid\",      [\"stockitemname\", \"brand\"], run_at)\n"
        "s5 = load_scd2(df_dm,   \"dimdeliverymethod\", \"deliverymethodkey\", \"deliverymethodid\", [\"deliverymethodname\"], run_at)\n"
        "s6 = load_scd2(df_pm,   \"dimpaymentmethod\",  \"paymentmethodkey\",  \"paymentmethodid\",  [\"paymentmethodname\"], run_at)\n"
        "\n"
        "print(f\"DimEmployee:        {s1}\")\n"
        "print(f\"DimCustomer:        {s2}\")\n"
        "print(f\"DimLocation:        {s3}\")\n"
        "print(f\"DimProduct:         {s4}\")\n"
        "print(f\"DimDeliveryMethod:  {s5}\")\n"
        "print(f\"DimPaymentMethod:   {s6}\")\n"
    ))

    cells.append(md(
        "## 5. Facts — FactSales and FactInvoices\n"
        "\n"
        "Surrogate-key lookups come from current dim rows (`date_to IS NULL`). Unmapped business keys are reported but still load as NULL — the quality script catches them with the unmapped-FK check."
    ))
    cells.append(code(
        "def get_dim_keys(conn, table, business_key, surrogate_key):\n"
        "    df = pd.read_sql(text(f\"SELECT {business_key}, {surrogate_key} FROM gold.{table} WHERE date_to IS NULL\"), conn)\n"
        "    return df.set_index(business_key)[surrogate_key].to_dict()\n"
        "\n"
        "with engine.connect() as conn:\n"
        "    df_f_sales = pd.read_sql(text(\"SELECT * FROM silver.stg_fact_sales\"), conn)\n"
        "    df_f_inv   = pd.read_sql(text(\"SELECT * FROM silver.stg_fact_invoices\"), conn)\n"
        "    emp_map  = get_dim_keys(conn, \"dimemployee\",       \"personid\",          \"employeekey\")\n"
        "    cust_map = get_dim_keys(conn, \"dimcustomer\",       \"customerid\",        \"customerkey\")\n"
        "    loc_map  = get_dim_keys(conn, \"dimlocation\",       \"locationid\",        \"locationkey\")\n"
        "    prod_map = get_dim_keys(conn, \"dimproduct\",        \"stockitemid\",       \"productkey\")\n"
        "    dm_map   = get_dim_keys(conn, \"dimdeliverymethod\", \"deliverymethodid\",  \"deliverymethodkey\")\n"
        "\n"
        "def warn_unmapped(df, biz_col, key_col, label):\n"
        "    unmapped = df[biz_col].notna() & df[key_col].isna()\n"
        "    if unmapped.any():\n"
        "        print(f\"⚠ {label}: {int(unmapped.sum())} rows with {biz_col} not in dim — will be NULL\")\n"
        "\n"
        "if not df_f_sales.empty:\n"
        "    df_f_sales[\"datekey\"] = pd.to_datetime(df_f_sales[\"invoicedate\"]).dt.strftime(\"%Y%m%d\").astype(int)\n"
        "    df_f_sales[\"employeekey\"] = df_f_sales[\"salespersonpersonid\"].map(emp_map)\n"
        "    df_f_sales[\"customerkey\"] = df_f_sales[\"customerid\"].map(cust_map)\n"
        "    df_f_sales[\"productkey\"]  = df_f_sales[\"stockitemid\"].map(prod_map)\n"
        "    df_f_sales[\"locationkey\"] = df_f_sales[\"deliverycityid\"].map(loc_map)\n"
        "    warn_unmapped(df_f_sales, \"salespersonpersonid\", \"employeekey\", \"FactSales.employeekey\")\n"
        "    warn_unmapped(df_f_sales, \"customerid\",          \"customerkey\", \"FactSales.customerkey\")\n"
        "    warn_unmapped(df_f_sales, \"stockitemid\",         \"productkey\",  \"FactSales.productkey\")\n"
        "    warn_unmapped(df_f_sales, \"deliverycityid\",      \"locationkey\", \"FactSales.locationkey\")\n"
        "    factsales = df_f_sales[[\n"
        "        \"invoiceid\", \"datekey\", \"employeekey\", \"customerkey\", \"productkey\", \"locationkey\",\n"
        "        \"quantity\", \"unitprice\", \"taxamount\", \"extendedprice\", \"lineprofit\"\n"
        "    ]]\n"
        "    with engine.begin() as conn:\n"
        "        conn.execute(text(\"TRUNCATE TABLE gold.factsales CASCADE\"))\n"
        "        factsales.where(pd.notna(factsales), None).to_sql(\"factsales\", conn, schema=\"gold\", if_exists=\"append\", index=False)\n"
        "    print(f\"✓ FactSales: {len(factsales)} loaded.\")\n"
        "\n"
        "if not df_f_inv.empty:\n"
        "    df_f_inv[\"datekey\"] = pd.to_datetime(df_f_inv[\"invoicedate\"]).dt.strftime(\"%Y%m%d\").astype(int)\n"
        "    df_f_inv[\"employeekey\"]         = df_f_inv[\"salespersonpersonid\"].map(emp_map)\n"
        "    df_f_inv[\"accountsemployeekey\"] = df_f_inv[\"accountspersonid\"].map(emp_map)\n"
        "    df_f_inv[\"customerkey\"]         = df_f_inv[\"customerid\"].map(cust_map)\n"
        "    df_f_inv[\"locationkey\"]         = df_f_inv[\"deliverycityid\"].map(loc_map)\n"
        "    df_f_inv[\"deliverymethodkey\"]   = df_f_inv[\"deliverymethodid\"].map(dm_map) if \"deliverymethodid\" in df_f_inv.columns else None\n"
        "    warn_unmapped(df_f_inv, \"customerid\",       \"customerkey\",        \"FactInvoices.customerkey\")\n"
        "    warn_unmapped(df_f_inv, \"deliverymethodid\", \"deliverymethodkey\",  \"FactInvoices.deliverymethodkey\")\n"
        "    factinvoices = df_f_inv[[\n"
        "        \"invoiceid\", \"datekey\", \"employeekey\", \"customerkey\", \"locationkey\",\n"
        "        \"accountsemployeekey\", \"deliverymethodkey\",\n"
        "        \"invoiceamount\", \"paymentdelay_days\", \"outstandingbalance\"\n"
        "    ]]\n"
        "    with engine.begin() as conn:\n"
        "        conn.execute(text(\"TRUNCATE TABLE gold.factinvoices CASCADE\"))\n"
        "        factinvoices.where(pd.notna(factinvoices), None).to_sql(\"factinvoices\", conn, schema=\"gold\", if_exists=\"append\", index=False)\n"
        "    print(f\"✓ FactInvoices: {len(factinvoices)} loaded.\")\n"
    ))

    cells.append(md(
        "## 6. Apply indexes and run quality checks"
    ))
    cells.append(code(
        "from pathlib import Path\n"
        "import subprocess\n"
        "import sys\n"
        "\n"
        "sql_path = Path(\"scripts\") / \"create_indexes_and_constraints.sql\"\n"
        "if sql_path.exists():\n"
        "    sql = sql_path.read_text(encoding=\"utf-8\")\n"
        "    try:\n"
        "        with engine.begin() as conn:\n"
        "            conn.execute(text(sql))\n"
        "        print(\"✓ Indexes and constraints applied.\")\n"
        "    except Exception as e:\n"
        "        print(f\"✗ Index error: {e}\")\n"
        "else:\n"
        "    print(\"Index script not found:\", sql_path)\n"
        "\n"
        "print(\"\\nRunning 04_quality_checks.py ...\")\n"
        "res = subprocess.run([sys.executable, \"04_quality_checks.py\"], check=False)\n"
        "print(\"Quality checks exit code:\", res.returncode)\n"
    ))

    nb["cells"] = cells
    nb_path.write_text(json.dumps(nb, indent=1, ensure_ascii=False), encoding="utf-8")
    print(f"Patched {nb_path.name}: {len(cells)} cells")


if __name__ == "__main__":
    patch_setup()
    patch_bronze()
    patch_silver()
    patch_gold()
